[package]
name = "macro-trace-object"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.37"
syn = { version = "1.0.91", features = ["extra-traits"] }
quote = "1.0.18"
proc-macro-error = "1.0.4"
