name: Check mmtk-dev-env

# Triggerred when a new commit is pushed to master
on:
  push:
    branches:
      - master

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Trigger ci.yml from mmtk/mmtk-dev-env to make sure mmtk-core can build with mmtk-dev-env.
  check-mmtk-dev-env:
    runs-on: ubuntu-22.04
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: mmtk
          repo: mmtk-dev-env
          github_token: ${{ secrets.CI_ACCESS_TOKEN }}
          workflow_file_name: ci.yml
          ref: main
          wait_interval: 30
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
